[workspace]
members = [
    "crates/flowrs-core",
    "crates/flowrs-transform",
    "crates/flowrs-event",
    "crates/flowrs-timer",
    "crates/flowrs-longrunning",
    "crates/flowrs-reactive",
    "benches",
]
resolver = "2"

[workspace.package]
version = "1.0.3"
edition = "2021"
authors = ["Flowrs Contributors"]
license = "MIT"
repository = "https://github.com/aitoroses/flowrs"
readme = "README.md"
description = "A directed graph workflow system in Rust"
keywords = ["workflow", "graph", "async", "pipeline", "directed-graph"]
categories = ["asynchronous", "concurrency", "data-structures"]
homepage = "https://github.com/aitoroses/flowrs"
documentation = "https://docs.rs/flowrs"

[workspace.dependencies]
tokio = { version = "1.43", features = ["full"] }
async-trait = "0.1.77"
thiserror = "1.0.58"
tracing = "0.1.40"
futures = "0.3.30"
uuid = { version = "1.6.1", features = ["v4", "serde"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.112"
chrono = { version = "0.4.34", features = ["serde"] }
rand = "0.8.5"
tracing-subscriber = "0.3.18"
criterion = "0.5.1"
tokio-stream = "0.1.17"

# Create a library target at the root to make examples work
[package]
name = "flowrs"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description.workspace = true

# Define features
[features]
default = ["core"]
core = ["flowrs-core"]
transform = ["core", "flowrs-transform"]
event = ["core", "flowrs-event"]
timer = ["core", "flowrs-timer"]
longrunning = ["core", "flowrs-longrunning"]
reactive = ["core", "flowrs-reactive"]
full = ["transform", "event", "timer", "longrunning", "reactive"]

[dependencies]
# Core dependencies (always included)
tokio.workspace = true
async-trait.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
futures.workspace = true
rand.workspace = true
uuid.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio-stream.workspace = true

# Feature-gated dependencies
flowrs-core = { path = "./crates/flowrs-core", version = "1.0.2", optional = true }
flowrs-transform = { path = "./crates/flowrs-transform", version = "1.0.2", optional = true }
flowrs-event = { path = "./crates/flowrs-event", version = "=1.0.3", optional = true }
flowrs-timer = { path = "./crates/flowrs-timer", version = "=1.0.3", optional = true }
flowrs-longrunning = { path = "./crates/flowrs-longrunning", version = "=1.0.3", optional = true }
flowrs-reactive = { path = "./crates/flowrs-reactive", version = "=1.0.3", optional = true }

# Example configurations
[[example]]
name = "lifecycle_node"
path = "examples/lifecycle_node.rs"
required-features = ["core"]

[[example]]
name = "transform_node"
path = "examples/transform_node.rs"
required-features = ["transform"]

[[example]]
name = "transform_node_example"
path = "examples/transform_node_example.rs"
required-features = ["transform"]

[[example]]
name = "order_processing"
path = "examples/order_processing.rs"
required-features = ["core"]

[[example]]
name = "batch_processing"
path = "examples/batch_processing.rs"
required-features = ["core"]

[[example]]
name = "event_driven_workflow"
path = "examples/event_driven_workflow.rs"
required-features = ["event"]

[[example]]
name = "reactive_node"
path = "examples/reactive_node.rs"
required-features = ["reactive"]

[[example]]
name = "timer_node"
path = "examples/timer_node.rs"
required-features = ["timer"]

[[example]]
name = "longrunning_node"
path = "examples/longrunning_node.rs"
required-features = ["longrunning"]

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
strip = "symbols"
lto = "thin"
codegen-units = 1
