# Configuration for cargo-release
# See: https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md

# Don't push changes automatically
push = false

# Don't publish to crates.io automatically
publish = false

# Don't create a tag automatically
tag = false

# Don't create a GitHub release automatically
release = false

# Don't update dependencies automatically
dependent-version = "fix"

# Use conventional commits for changelog generation
pre-release-commit-message = "chore(release): {{version}}"
