name: Release

on:
  push:
    tags:
      - "v*"

# Sets permissions of the GITHUB_TOKEN to allow creating releases
permissions:
  contents: write # Needed for creating GitHub releases

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Verify tag version matches Cargo.toml
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          CARGO_VERSION=$(grep -m 1 'version = ' Cargo.toml | cut -d '"' -f 2)
          if [ "$TAG_VERSION" != "$CARGO_VERSION" ]; then
            echo "Tag version ($TAG_VERSION) does not match Cargo.toml version ($CARGO_VERSION)"
            exit 1
          fi

      - name: Run tests
        run: cargo test --all-features

      # Publish crates in dependency order
      - name: Publish flowrs-core
        working-directory: ./crates/flowrs-core
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}

      - name: Wait for crates.io indexing
        run: sleep 15

      - name: Publish flowrs-transform
        working-directory: ./crates/flowrs-transform
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}

      - name: Wait for crates.io indexing
        run: sleep 15

      - name: Publish flowrs-event
        working-directory: ./crates/flowrs-event
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}

      - name: Wait for crates.io indexing
        run: sleep 15

      - name: Publish flowrs-timer
        working-directory: ./crates/flowrs-timer
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}

      - name: Wait for crates.io indexing
        run: sleep 15

      - name: Publish flowrs-longrunning
        working-directory: ./crates/flowrs-longrunning
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}

      - name: Wait for crates.io indexing
        run: sleep 15

      - name: Publish flowrs-reactive
        working-directory: ./crates/flowrs-reactive
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}

      - name: Wait for crates.io indexing
        run: sleep 15

      - name: Publish flowrs (root)
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          prerelease: ${{ contains(github.ref, '-alpha') || contains(github.ref, '-beta') || contains(github.ref, '-rc') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
