name: Version Bump

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: "Version bump type"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
      dry_run:
        description: "Dry run (no commits)"
        required: true
        type: boolean
        default: true

# Sets permissions of the GITHUB_TOKEN to allow pushing to the repository
permissions:
  contents: write # Needed to push commits and tags

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install cargo-workspaces
        run: cargo install cargo-workspaces

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Bump versions
        run: |
          if [ "${{ github.event.inputs.dry_run }}" = "true" ]; then
            cargo workspaces version ${{ github.event.inputs.bump_type }} --no-git-commit --exact --yes
          else
            cargo workspaces version ${{ github.event.inputs.bump_type }} --exact --yes
            
            # Get the new version
            NEW_VERSION=$(grep -m 1 'version = ' Cargo.toml | cut -d '"' -f 2)
            
            # Create and push tag
            git tag -a "v${NEW_VERSION}" -m "Release v${NEW_VERSION}"
            git push origin "v${NEW_VERSION}"
          fi
